# -*- coding: utf-8 -*-
"""Convolucional Personagens.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PSbF4T7q3Ox79iMrzNSfMq27URunNc-n

# Rede neural convolucional - personagens

## Importação das bibliotecas
"""

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import zipfile
tf.__version__

"""## Carregamento das imagens"""

from google.colab import drive
drive.mount('/content/drive')

path = '/content/personagens.zip'
zip_object = zipfile.ZipFile(file=path, mode='r')
zip_object.extractall('./')
zip_object.close()

tf.keras.preprocessing.image.load_img(r'/content/training_set/bart/bart100.bmp')

tf.keras.preprocessing.image.load_img(r'/content/training_set/homer/homer100.bmp')

"""## Construção das bases de treinamento e teste"""

gerador_treinamento = ImageDataGenerator(rescale=1./255,
                                         rotation_range=7,
                                         horizontal_flip=True,
                                         zoom_range=0.2)
base_treinamento = gerador_treinamento.flow_from_directory('/content/training_set',
                                                           target_size = (64, 64),
                                                           batch_size = 8,
                                                           class_mode = 'categorical')

base_treinamento.classes

base_treinamento.class_indices

gerador_teste = ImageDataGenerator(rescale=1./255)
base_teste = gerador_teste.flow_from_directory('/content/test_set', #Atualizado: 02/05/2021 - Linha corrigida: gerador_treinamento.flow_from_director --> gerador_teste.flow_from_directory
                                                     target_size = (64, 64),
                                                     batch_size = 8,
                                                     class_mode = 'categorical',
                                                     shuffle = False)

"""## Construção e treinamento da rede neural"""

rede_neural = Sequential()
rede_neural.add(Conv2D(32, (3,3), input_shape = (64,64,3), activation='relu'))
rede_neural.add(MaxPooling2D(pool_size=(2,2)))

rede_neural.add(Conv2D(32, (3,3), activation='relu'))
rede_neural.add(MaxPooling2D(pool_size=(2,2)))

rede_neural.add(Flatten())

rede_neural.add(Dense(units = 4, activation='relu'))
rede_neural.add(Dense(units = 4, activation='relu'))
rede_neural.add(Dense(units = 2, activation='softmax'))

rede_neural.compile(optimizer='adam', loss='categorical_crossentropy',
                    metrics = ['accuracy'])

rede_neural.fit_generator(base_treinamento, epochs=100, validation_data=base_teste)

"""## Avaliação da rede neural"""

base_teste.class_indices

previsoes = rede_neural.predict(base_teste)
previsoes

import numpy as np
previsoes2 = np.argmax(previsoes, axis = 1)
previsoes2

base_teste.classes

from sklearn.metrics import accuracy_score
accuracy_score(previsoes2, base_teste.classes)

base_teste.class_indices

from sklearn.metrics import confusion_matrix
import seaborn as sns
cm = confusion_matrix(previsoes2, base_teste.classes)
sns.heatmap(cm, annot=True)