# -*- coding: utf-8 -*-
"""Gorgetas - Exercício.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IgM82kDzToHmsWyDTEy5NoM_SiCyTWXR

Olá,

Conforme comentado na aula teórica, é possível configurar outros tipos de funções de membership. O objetivo desta tarefa é testar outras funções e comparar os resultados com o código que implementamos anteriormente. Tente executar as modificações abaixo e use outros valores de parâmetros para fazer os testes (consulte a documentação do skfuzzy para entender melhor o que é cada valor)

    gorjeta['baixa'] = fuzz.sigmf(gorjeta.universe, 5, -1)
    gorjeta['media'] = fuzz.gaussmf(gorjeta.universe, 10, 3)
    gorjeta['alta'] = fuzz.pimf(gorjeta.universe, 10, 20, 20, 21)

Bom trabalho!

# Fuzzy - exemplo das gorgetas

**Antecedentes (entradas)**

Serviço: que nota você daria para o serviço, em uma escala de 0 a 10?
- ruim, aceitável, ótimo

Qualidade da comida: quão boa estava a comida, em uma escala de 0 a 10?
- ruim, boa, saborosa

**Consequentes (saídas)**

Gorjeta: quanta gorjeta você daria, entre 0% e 20%?
- baixa, média, alta

Regras
- Se a qualidade da comida for *ruim* ou o serviço for *ruim* então a gorjeta será *baixa*
- Se o serviço for *médio* então a gorjeta será *média*
- Se o serviço for *bom* e a qualidade da comida for *boa* então a gorjeta será *alta*

## Instalação e importação das bibliotecas
"""

!pip install scikit-fuzzy

import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl

"""## Antecedentes e consequente"""

qualidade = ctrl.Antecedent(np.arange(0, 11, 1), 'qualidade')
servico = ctrl.Antecedent(np.arange(0, 11, 1), 'servico')

gorjeta = ctrl.Consequent(np.arange(0, 21, 1), 'gorjeta')

"""## Membership functions"""

qualidade.automf(number=3, names=['ruim', 'boa', 'saborosa'])
servico.automf(number=3, names=['ruim', 'aceitável', 'ótimo'])

gorjeta['baixa'] = fuzz.sigmf(gorjeta.universe, 5, -1)
gorjeta['media'] = fuzz.gaussmf(gorjeta.universe, 10, 3)
gorjeta['alta'] = fuzz.pimf(gorjeta.universe, 10, 20, 20, 21)
gorjeta.view()

regra1 = ctrl.Rule(qualidade['ruim'] | servico['ruim'], gorjeta['baixa'])
regra2 = ctrl.Rule(servico['aceitável'], gorjeta['media'])
regra3 = ctrl.Rule(servico['ótimo'] | qualidade['saborosa'], gorjeta['alta'])

"""## Sistema de controle"""

sistema_controle = ctrl.ControlSystem([regra1, regra2, regra3])

sistema = ctrl.ControlSystemSimulation(sistema_controle)

sistema.input['qualidade'] = 1
sistema.input['servico'] = 1
sistema.compute()

print(sistema.output['gorjeta'])
gorjeta.view(sim=sistema)